In [1]:
import pandas as pd
import scipy.stats as ss

In [2]:
from IPython.display import IFrame
url = 'https://co.marca.com/claro/futbol-internacional/bundesliga/posiciones.html'
IFrame(url, width=970, height=600)

 ## Cargando datos de Bundesliga

In [3]:
data_file = "../data/original/bundesliga.csv"
data = pd.read_csv(data_file, engine='python')
data.shape

(18, 23)

In [4]:
tabla_equipos = data[['ID', 'Equipo']]
tabla_equipos.head(18)

    ID                    Equipo
0    1             Bayern Munich
1    2         Borussia Dortmund
2    3                   Leipzig
3    4  Borussia Manchengladbach
4    5       Bayer 04 Leverkusen
5    6                Wolfsburgo
6    7                Schalke 04
7    8       TSG 1899 Hoffenheim
8    9                  Friburgo
9   10             Hertha Berlin
10  11                   Colonia
11  12                 Augsburgo
12  13        1. FC Union Berlin
13  14       Eintracht Frankfurt
14  15                  Mainz 05
15  16       Fortuna D�usseldorf
16  17             Werder Bremen
17  18           SC Paderborn 07

In [5]:
tabla_posiciones = data[['ID', 'Equipo', 'PT:Puntos Totales', 'PJ:Partidos Jugados', 'PG:Partidos Ganados', 'PE:Partidos Empatados', 'PP:Partidos Perdidos', 'GF:Goles a favor', 'GC:Goles en contra']]
tabla_posiciones.columns = ['ID', 'Equipo', 'pt', 'pj', 'pg', 'pe', 'pp', 'gf', 'gc']
tabla_posiciones.head(18)

    ID                    Equipo  pt  pj  pg  pe  pp  gf  gc
0    1             Bayern Munich  64  28  20   4   4  81  28
1    2         Borussia Dortmund  57  28  17   6   5  74  34
2    3                   Leipzig  55  28  15  10   3  70  29
3    4  Borussia Manchengladbach  53  28  16   5   7  53  34
4    5       Bayer 04 Leverkusen  53  28  16   5   7  53  36
5    6                Wolfsburgo  42  28  11   9   8  40  34
6    7                Schalke 04  40  28  10  10   8  34  43
7    8       TSG 1899 Hoffenheim  39  28  11   6  11  39  48
8    9                  Friburgo  38  28  10   8  10  38  40
9   10             Hertha Berlin  35  28   9   8  11  41  50
10  11                   Colonia  34  28  10   4  14  44  52
11  12                 Augsburgo  31  28   8   7  13  40  54
12  13        1. FC Union Berlin  31  28   9   4  15  33  48
13  14       Eintracht Frankfurt  29  27   8   5  14  44  52
14  15                  Mainz 05  28  28   8   4  16  37  61
15  16       Fortuna D�usseldorf  24  28   5   9  14  29  53
16  17             Werder Bremen  22  27   5   7  15  29  59
17  18           SC Paderborn 07  19  28   4   7  17  31  55

In [6]:
campaña_local = data[['ID', 'Equipo', 'PTL:Puntos Totales', 'PJL:Partidos Jugados', 'PGL:Partidos Ganados', 'PEL:Partidos Empatados', 'PPL:Partidos Perdidos', 'GFL:Goles a favor', 'GCL:Goles en contra']]
campaña_local.columns = ['ID', 'Equipo', 'pt', 'pj', 'pg', 'pe', 'pp', 'gf', 'gc']
campaña_local.head(18)

    ID                    Equipo  pt  pj  pg  pe  pp  gf  gc
0    1             Bayern Munich  32  14  10   2   2  43  13
1    2         Borussia Dortmund  33  14  10   3   1  45  11
2    3                   Leipzig  27  14   7   6   1  35  16
3    4  Borussia Manchengladbach  29  14   9   2   3  31  19
4    5       Bayer 04 Leverkusen  25  14   7   4   3  26  17
5    6                Wolfsburgo  18  14   4   6   4  16  15
6    7                Schalke 04  21  14   5   6   3  18  21
7    8       TSG 1899 Hoffenheim  19  15   6   1   8  22  35
8    9                  Friburgo  20  13   6   2   5  16  15
9   10             Hertha Berlin  15  14   4   3   7  18  28
10  11                   Colonia  21  14   6   3   5  24  20
11  12                 Augsburgo  19  14   5   4   5  25  23
12  13        1. FC Union Berlin  20  14   6   2   6  19  19
13  14       Eintracht Frankfurt  22  14   6   4   4  31  22
14  15                  Mainz 05  14  14   4   2   8  15  26
15  16       Fortuna D�usseldorf  13  14   3   4   7  13  24
16  17             Werder Bremen   6  13   1   3   9   9  30
17  18           SC Paderborn 07   8  14   2   2  10  18  32

In [7]:
campaña_visita = data[['ID', 'Equipo', 'PTV:Puntos Totales', 'PJV:Partidos Jugados', 'PGV:Partidos Ganados', 'PEV:Partidos Empatados', 'PPV:Partidos Perdidos', 'GFV:Goles a favor', 'GCV:Goles en contra']]
campaña_visita.columns = ['ID', 'Equipo', 'pt', 'pj', 'pg', 'pe', 'pp', 'gf', 'gc']
campaña_visita.head(18)

    ID                    Equipo  pt  pj  pg  pe  pp  gf  gc
0    1             Bayern Munich  32  14  10   2   2  38  15
1    2         Borussia Dortmund  24  14   7   3   4  29  23
2    3                   Leipzig  28  14   8   4   2  35  13
3    4  Borussia Manchengladbach  24  14   7   3   4  22  15
4    5       Bayer 04 Leverkusen  28  14   9   1   4  27  19
5    6                Wolfsburgo  24  14   7   3   4  24  19
6    7                Schalke 04  19  14   5   4   5  16  22
7    8       TSG 1899 Hoffenheim  20  13   5   5   3  17  13
8    9                  Friburgo  18  15   4   6   5  22  25
9   10             Hertha Berlin  20  14   5   5   4  23  22
10  11                   Colonia  13  14   4   1   9  20  32
11  12                 Augsburgo  12  14   3   3   8  15  31
12  13        1. FC Union Berlin  11  14   3   2   9  14  29
13  14       Eintracht Frankfurt   7  13   2   1  10  13  30
14  15                  Mainz 05  14  14   4   2   8  22  35
15  16       Fortuna D�usseldorf  11  14   2   5   7  16  29
16  17             Werder Bremen  16  14   4   4   6  20  29
17  18           SC Paderborn 07  11  14   2   5   7  13  23

In [8]:
media_goles_local = (campaña_local.gf.sum()/campaña_local.pj.sum())
media_goles_visita = (campaña_visita.gf.sum()/campaña_visita.pj.sum())

In [9]:
campaña_local['fal'] = campaña_local[['gf', 'pj']].apply(lambda x: (x.gf/x.pj)*media_goles_local, axis=1)
campaña_local['fdl'] = campaña_local[['gc', 'pj']].apply(lambda x: (x.gc/x.pj)/media_goles_visita, axis=1)
campaña_visita['fav'] = campaña_visita[['gf', 'pj']].apply(lambda x: (x.gf/x.pj) / media_goles_visita, axis=1)

D:\appz\anaconda\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
D:\appz\anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

D:\appz\anaconda\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [10]:
def ingresar_valor(texto, minval, maxval, restriccion, mostrar_titulo):
    valor = 0
    ciclo = 1
    print()
    if mostrar_titulo is True:
        print("Seleccione equipo")
        print()
        print(tabla_equipos)
    while ciclo == 1:
        print(texto)
        try:
            valor = int(input())
            if valor < minval:
                print("Debe ingresar valores mayor o igual a {}".format(minval))
                continue
            elif valor > maxval:
                print("Debe ingresar valores menor o igual a {}".format(maxval))
            if valor == restriccion:
                print("El equipo ya fue seleccionado")
            else:
                ciclo = 0
        except Exception:
            print("Ingresar solo valores numéricos")
    return valor

In [11]:
def mostrar_valores(titulo, df):
    print()
    print(titulo)
    print(df)
    print()
    return

In [12]:
def calcular_probabilidad(factorlocal, factorvisita, goles):
    resultados = []
    for i in range(goles):
        x = ss.poisson.pmf(k=i, mu=factorlocal)
        y = ss.poisson.pmf(k=i, mu=factorvisita)
        z = (x*y)
        resultados.append([i, x, y, z])
    return pd.DataFrame(resultados, columns=['Goles', 'Prob local', 'Prob visita', 'Prov total'])

In [13]:
def sumas(df, columna, inicio):
    suma = 0
    while inicio <= len(df)-1:
        suma = suma + df.at[df.index[inicio], columna]
        inicio += 1
    return suma

In [14]:
def calcular_valores(df, colprob, colsuma):
    tope = 0
    valor = 0
    for i in range(len(df)):
        tp = df.at[df.index[i], colprob]
        tope = len(df) if tope >= len(df) else tope + 1
        sp = sumas(df, colsuma, tope)
        valor = valor + (tp*sp)
    return valor

In [15]:
def mostrar_probabilidad_partido(df):
    prob_local = calcular_valores(df, 'Prob visita', 'Prob local')
    prob_empate = df['Prov total'].sum()
    prob_visita = calcular_valores(df, 'Prob local', 'Prob visita')
    print()
    print("Probabilidad de resultados: ")
    print("Local: {:,.2f}%".format((prob_local*100)))
    print("Empate: {:,.2f}%".format((prob_empate*100)))
    print("Visita: {:,.2f}%".format((prob_visita*100)))
    return

In [16]:
def extraer_tabla(df, idlocal, idvisita):
    df1 = df.loc[df["ID"] == idlocal, ]
    df2 = df.loc[df["ID"] == idvisita, ]
    return pd.concat([df1, df2], axis=0)

In [17]:
def obtener_equipos(idlocal, idvisita, goles):
    tp_equipos = extraer_tabla(tabla_posiciones, idlocal, idvisita)
    cl_equipos = extraer_tabla(campaña_local, idlocal, idvisita)
    cv_equipos = extraer_tabla(campaña_visita, idlocal, idvisita)
    fal_local = cl_equipos.at[cl_equipos.index[0], 'fal']
    fdl_local = cl_equipos.at[cl_equipos.index[0], 'fdl']
    fal_visita = cl_equipos.at[cl_equipos.index[-1], 'fal']
    fdl_visita = cl_equipos.at[cl_equipos.index[-1], 'fdl']
    factor_local = (fal_local*fdl_visita)*media_goles_local
    factor_visita = (fal_visita*fdl_local)/media_goles_visita
    prob_goles = calcular_probabilidad(factor_local, factor_visita, goles)
    mostrar_valores("Tabla de posiciones", tp_equipos)
    mostrar_valores("Campaña de local", cl_equipos)
    mostrar_valores("Campaña de visita", cv_equipos)
    mostrar_probabilidad_partido(prob_goles)
    return

In [19]:
local = ingresar_valor("Ingrese id equipo local: ", 1, len(tabla_equipos), 0, True)
visita = ingresar_valor("Ingrese id equipo visita: ", 1, len(tabla_equipos), local, True)
goles = ingresar_valor("Ingrese máximo de goles del partido: ", 0, 9, 10, False)
obtener_equipos(local, visita, goles)

Seleccione equipo

    ID                    Equipo
0    1             Bayern Munich
1    2         Borussia Dortmund
2    3                   Leipzig
3    4  Borussia Manchengladbach
4    5       Bayer 04 Leverkusen
5    6                Wolfsburgo
6    7                Schalke 04
7    8       TSG 1899 Hoffenheim
8    9                  Friburgo
9   10             Hertha Berlin
10  11                   Colonia
11  12                 Augsburgo
12  13        1. FC Union Berlin
13  14       Eintracht Frankfurt
14  15                  Mainz 05
15  16       Fortuna D�usseldorf
16  17             Werder Bremen
17  18           SC Paderborn 07
Ingrese id equipo local:
2

Seleccione equipo

    ID                    Equipo
0    1             Bayern Munich
1    2         Borussia Dortmund
2    3                   Leipzig
3    4  Borussia Manchengladbach
4    5       Bayer 04 Leverkusen
5    6                Wolfsburgo
6    7                Schalke 04
7    8       TSG 1899 Hoffenheim
8    9                  Friburgo
9   10             Hertha Berlin
10  11                   Colonia
11  12                 Augsburgo
12  13        1. FC Union Berlin
13  14       Eintracht Frankfurt
14  15                  Mainz 05
15  16       Fortuna D�usseldorf
16  17             Werder Bremen
17  18           SC Paderborn 07
Ingrese id equipo visita:
5

Ingrese máximo de goles del partido:
5

Tabla de posiciones
   ID               Equipo  pt  pj  pg  pe  pp  gf  gc
1   2    Borussia Dortmund  57  28  17   6   5  74  34
4   5  Bayer 04 Leverkusen  53  28  16   5   7  53  36


Campaña de local
   ID               Equipo  pt  pj  pg  pe  pp  gf  gc       fal       fdl
1   2    Borussia Dortmund  33  14  10   3   1  45  11  5.429710  0.510918
4   5  Bayer 04 Leverkusen  25  14   7   4   3  26  17  3.137166  0.789600


Campaña de visita
   ID               Equipo  pt  pj  pg  pe  pp  gf  gc       fav
1   2    Borussia Dortmund  24  14   7   3   4  29  23  1.346965
4   5  Bayer 04 Leverkusen  28  14   9   1   4  27  19  1.254071


Probabilidad de resultados:
Local: 13.69%
Empate: 1.02%
Visita: 0.42%